// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mmo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mmo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mmo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mmo_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mmo_2eproto;
class MoveBroadcast;
struct MoveBroadcastDefaultTypeInternal;
extern MoveBroadcastDefaultTypeInternal _MoveBroadcast_default_instance_;
class MoveRequest;
struct MoveRequestDefaultTypeInternal;
extern MoveRequestDefaultTypeInternal _MoveRequest_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::MoveBroadcast* Arena::CreateMaybeMessage<::MoveBroadcast>(Arena*);
template<> ::MoveRequest* Arena::CreateMaybeMessage<::MoveRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class MoveRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MoveRequest) */ {
 public:
  inline MoveRequest() : MoveRequest(nullptr) {}
  ~MoveRequest() override;
  explicit PROTOBUF_CONSTEXPR MoveRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MoveRequest(const MoveRequest& from);
  MoveRequest(MoveRequest&& from) noexcept
    : MoveRequest() {
    *this = ::std::move(from);
  }

  inline MoveRequest& operator=(const MoveRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MoveRequest& operator=(MoveRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MoveRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const MoveRequest* internal_default_instance() {
    return reinterpret_cast<const MoveRequest*>(
               &_MoveRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MoveRequest& a, MoveRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(MoveRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MoveRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MoveRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MoveRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MoveRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MoveRequest& from) {
    MoveRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MoveRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MoveRequest";
  }
  protected:
  explicit MoveRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kPositionXFieldNumber = 2,
    kPositionYFieldNumber = 3,
    kPositionZFieldNumber = 4,
    kRotationYFieldNumber = 5,
    kVelocityXFieldNumber = 6,
    kVelocityYFieldNumber = 7,
    kVelocityZFieldNumber = 8,
    kHorizontalFieldNumber = 9,
    kVerticalFieldNumber = 10,
    kTimestampFieldNumber = 11,
  };
  // uint32 player_id = 1;
  void clear_player_id();
  uint32_t player_id() const;
  void set_player_id(uint32_t value);
  private:
  uint32_t _internal_player_id() const;
  void _internal_set_player_id(uint32_t value);
  public:

  // float position_x = 2;
  void clear_position_x();
  float position_x() const;
  void set_position_x(float value);
  private:
  float _internal_position_x() const;
  void _internal_set_position_x(float value);
  public:

  // float position_y = 3;
  void clear_position_y();
  float position_y() const;
  void set_position_y(float value);
  private:
  float _internal_position_y() const;
  void _internal_set_position_y(float value);
  public:

  // float position_z = 4;
  void clear_position_z();
  float position_z() const;
  void set_position_z(float value);
  private:
  float _internal_position_z() const;
  void _internal_set_position_z(float value);
  public:

  // float rotation_y = 5;
  void clear_rotation_y();
  float rotation_y() const;
  void set_rotation_y(float value);
  private:
  float _internal_rotation_y() const;
  void _internal_set_rotation_y(float value);
  public:

  // float velocity_x = 6;
  void clear_velocity_x();
  float velocity_x() const;
  void set_velocity_x(float value);
  private:
  float _internal_velocity_x() const;
  void _internal_set_velocity_x(float value);
  public:

  // float velocity_y = 7;
  void clear_velocity_y();
  float velocity_y() const;
  void set_velocity_y(float value);
  private:
  float _internal_velocity_y() const;
  void _internal_set_velocity_y(float value);
  public:

  // float velocity_z = 8;
  void clear_velocity_z();
  float velocity_z() const;
  void set_velocity_z(float value);
  private:
  float _internal_velocity_z() const;
  void _internal_set_velocity_z(float value);
  public:

  // float horizontal = 9;
  void clear_horizontal();
  float horizontal() const;
  void set_horizontal(float value);
  private:
  float _internal_horizontal() const;
  void _internal_set_horizontal(float value);
  public:

  // float vertical = 10;
  void clear_vertical();
  float vertical() const;
  void set_vertical(float value);
  private:
  float _internal_vertical() const;
  void _internal_set_vertical(float value);
  public:

  // uint64 timestamp = 11;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:MoveRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t player_id_;
    float position_x_;
    float position_y_;
    float position_z_;
    float rotation_y_;
    float velocity_x_;
    float velocity_y_;
    float velocity_z_;
    float horizontal_;
    float vertical_;
    uint64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mmo_2eproto;
};
// -------------------------------------------------------------------

class MoveBroadcast final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MoveBroadcast) */ {
 public:
  inline MoveBroadcast() : MoveBroadcast(nullptr) {}
  ~MoveBroadcast() override;
  explicit PROTOBUF_CONSTEXPR MoveBroadcast(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MoveBroadcast(const MoveBroadcast& from);
  MoveBroadcast(MoveBroadcast&& from) noexcept
    : MoveBroadcast() {
    *this = ::std::move(from);
  }

  inline MoveBroadcast& operator=(const MoveBroadcast& from) {
    CopyFrom(from);
    return *this;
  }
  inline MoveBroadcast& operator=(MoveBroadcast&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MoveBroadcast& default_instance() {
    return *internal_default_instance();
  }
  static inline const MoveBroadcast* internal_default_instance() {
    return reinterpret_cast<const MoveBroadcast*>(
               &_MoveBroadcast_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MoveBroadcast& a, MoveBroadcast& b) {
    a.Swap(&b);
  }
  inline void Swap(MoveBroadcast* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MoveBroadcast* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MoveBroadcast* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MoveBroadcast>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MoveBroadcast& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MoveBroadcast& from) {
    MoveBroadcast::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MoveBroadcast* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MoveBroadcast";
  }
  protected:
  explicit MoveBroadcast(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kPositionXFieldNumber = 2,
    kPositionYFieldNumber = 3,
    kPositionZFieldNumber = 4,
    kServerTimeFieldNumber = 6,
    kRotationYFieldNumber = 5,
    kStateFieldNumber = 7,
  };
  // uint32 player_id = 1;
  void clear_player_id();
  uint32_t player_id() const;
  void set_player_id(uint32_t value);
  private:
  uint32_t _internal_player_id() const;
  void _internal_set_player_id(uint32_t value);
  public:

  // float position_x = 2;
  void clear_position_x();
  float position_x() const;
  void set_position_x(float value);
  private:
  float _internal_position_x() const;
  void _internal_set_position_x(float value);
  public:

  // float position_y = 3;
  void clear_position_y();
  float position_y() const;
  void set_position_y(float value);
  private:
  float _internal_position_y() const;
  void _internal_set_position_y(float value);
  public:

  // float position_z = 4;
  void clear_position_z();
  float position_z() const;
  void set_position_z(float value);
  private:
  float _internal_position_z() const;
  void _internal_set_position_z(float value);
  public:

  // uint64 server_time = 6;
  void clear_server_time();
  uint64_t server_time() const;
  void set_server_time(uint64_t value);
  private:
  uint64_t _internal_server_time() const;
  void _internal_set_server_time(uint64_t value);
  public:

  // float rotation_y = 5;
  void clear_rotation_y();
  float rotation_y() const;
  void set_rotation_y(float value);
  private:
  float _internal_rotation_y() const;
  void _internal_set_rotation_y(float value);
  public:

  // uint32 state = 7;
  void clear_state();
  uint32_t state() const;
  void set_state(uint32_t value);
  private:
  uint32_t _internal_state() const;
  void _internal_set_state(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:MoveBroadcast)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t player_id_;
    float position_x_;
    float position_y_;
    float position_z_;
    uint64_t server_time_;
    float rotation_y_;
    uint32_t state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mmo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MoveRequest

// uint32 player_id = 1;
inline void MoveRequest::clear_player_id() {
  _impl_.player_id_ = 0u;
}
inline uint32_t MoveRequest::_internal_player_id() const {
  return _impl_.player_id_;
}
inline uint32_t MoveRequest::player_id() const {
  // @@protoc_insertion_point(field_get:MoveRequest.player_id)
  return _internal_player_id();
}
inline void MoveRequest::_internal_set_player_id(uint32_t value) {
  
  _impl_.player_id_ = value;
}
inline void MoveRequest::set_player_id(uint32_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:MoveRequest.player_id)
}

// float position_x = 2;
inline void MoveRequest::clear_position_x() {
  _impl_.position_x_ = 0;
}
inline float MoveRequest::_internal_position_x() const {
  return _impl_.position_x_;
}
inline float MoveRequest::position_x() const {
  // @@protoc_insertion_point(field_get:MoveRequest.position_x)
  return _internal_position_x();
}
inline void MoveRequest::_internal_set_position_x(float value) {
  
  _impl_.position_x_ = value;
}
inline void MoveRequest::set_position_x(float value) {
  _internal_set_position_x(value);
  // @@protoc_insertion_point(field_set:MoveRequest.position_x)
}

// float position_y = 3;
inline void MoveRequest::clear_position_y() {
  _impl_.position_y_ = 0;
}
inline float MoveRequest::_internal_position_y() const {
  return _impl_.position_y_;
}
inline float MoveRequest::position_y() const {
  // @@protoc_insertion_point(field_get:MoveRequest.position_y)
  return _internal_position_y();
}
inline void MoveRequest::_internal_set_position_y(float value) {
  
  _impl_.position_y_ = value;
}
inline void MoveRequest::set_position_y(float value) {
  _internal_set_position_y(value);
  // @@protoc_insertion_point(field_set:MoveRequest.position_y)
}

// float position_z = 4;
inline void MoveRequest::clear_position_z() {
  _impl_.position_z_ = 0;
}
inline float MoveRequest::_internal_position_z() const {
  return _impl_.position_z_;
}
inline float MoveRequest::position_z() const {
  // @@protoc_insertion_point(field_get:MoveRequest.position_z)
  return _internal_position_z();
}
inline void MoveRequest::_internal_set_position_z(float value) {
  
  _impl_.position_z_ = value;
}
inline void MoveRequest::set_position_z(float value) {
  _internal_set_position_z(value);
  // @@protoc_insertion_point(field_set:MoveRequest.position_z)
}

// float rotation_y = 5;
inline void MoveRequest::clear_rotation_y() {
  _impl_.rotation_y_ = 0;
}
inline float MoveRequest::_internal_rotation_y() const {
  return _impl_.rotation_y_;
}
inline float MoveRequest::rotation_y() const {
  // @@protoc_insertion_point(field_get:MoveRequest.rotation_y)
  return _internal_rotation_y();
}
inline void MoveRequest::_internal_set_rotation_y(float value) {
  
  _impl_.rotation_y_ = value;
}
inline void MoveRequest::set_rotation_y(float value) {
  _internal_set_rotation_y(value);
  // @@protoc_insertion_point(field_set:MoveRequest.rotation_y)
}

// float velocity_x = 6;
inline void MoveRequest::clear_velocity_x() {
  _impl_.velocity_x_ = 0;
}
inline float MoveRequest::_internal_velocity_x() const {
  return _impl_.velocity_x_;
}
inline float MoveRequest::velocity_x() const {
  // @@protoc_insertion_point(field_get:MoveRequest.velocity_x)
  return _internal_velocity_x();
}
inline void MoveRequest::_internal_set_velocity_x(float value) {
  
  _impl_.velocity_x_ = value;
}
inline void MoveRequest::set_velocity_x(float value) {
  _internal_set_velocity_x(value);
  // @@protoc_insertion_point(field_set:MoveRequest.velocity_x)
}

// float velocity_y = 7;
inline void MoveRequest::clear_velocity_y() {
  _impl_.velocity_y_ = 0;
}
inline float MoveRequest::_internal_velocity_y() const {
  return _impl_.velocity_y_;
}
inline float MoveRequest::velocity_y() const {
  // @@protoc_insertion_point(field_get:MoveRequest.velocity_y)
  return _internal_velocity_y();
}
inline void MoveRequest::_internal_set_velocity_y(float value) {
  
  _impl_.velocity_y_ = value;
}
inline void MoveRequest::set_velocity_y(float value) {
  _internal_set_velocity_y(value);
  // @@protoc_insertion_point(field_set:MoveRequest.velocity_y)
}

// float velocity_z = 8;
inline void MoveRequest::clear_velocity_z() {
  _impl_.velocity_z_ = 0;
}
inline float MoveRequest::_internal_velocity_z() const {
  return _impl_.velocity_z_;
}
inline float MoveRequest::velocity_z() const {
  // @@protoc_insertion_point(field_get:MoveRequest.velocity_z)
  return _internal_velocity_z();
}
inline void MoveRequest::_internal_set_velocity_z(float value) {
  
  _impl_.velocity_z_ = value;
}
inline void MoveRequest::set_velocity_z(float value) {
  _internal_set_velocity_z(value);
  // @@protoc_insertion_point(field_set:MoveRequest.velocity_z)
}

// float horizontal = 9;
inline void MoveRequest::clear_horizontal() {
  _impl_.horizontal_ = 0;
}
inline float MoveRequest::_internal_horizontal() const {
  return _impl_.horizontal_;
}
inline float MoveRequest::horizontal() const {
  // @@protoc_insertion_point(field_get:MoveRequest.horizontal)
  return _internal_horizontal();
}
inline void MoveRequest::_internal_set_horizontal(float value) {
  
  _impl_.horizontal_ = value;
}
inline void MoveRequest::set_horizontal(float value) {
  _internal_set_horizontal(value);
  // @@protoc_insertion_point(field_set:MoveRequest.horizontal)
}

// float vertical = 10;
inline void MoveRequest::clear_vertical() {
  _impl_.vertical_ = 0;
}
inline float MoveRequest::_internal_vertical() const {
  return _impl_.vertical_;
}
inline float MoveRequest::vertical() const {
  // @@protoc_insertion_point(field_get:MoveRequest.vertical)
  return _internal_vertical();
}
inline void MoveRequest::_internal_set_vertical(float value) {
  
  _impl_.vertical_ = value;
}
inline void MoveRequest::set_vertical(float value) {
  _internal_set_vertical(value);
  // @@protoc_insertion_point(field_set:MoveRequest.vertical)
}

// uint64 timestamp = 11;
inline void MoveRequest::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t MoveRequest::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t MoveRequest::timestamp() const {
  // @@protoc_insertion_point(field_get:MoveRequest.timestamp)
  return _internal_timestamp();
}
inline void MoveRequest::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void MoveRequest::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:MoveRequest.timestamp)
}

// -------------------------------------------------------------------

// MoveBroadcast

// uint32 player_id = 1;
inline void MoveBroadcast::clear_player_id() {
  _impl_.player_id_ = 0u;
}
inline uint32_t MoveBroadcast::_internal_player_id() const {
  return _impl_.player_id_;
}
inline uint32_t MoveBroadcast::player_id() const {
  // @@protoc_insertion_point(field_get:MoveBroadcast.player_id)
  return _internal_player_id();
}
inline void MoveBroadcast::_internal_set_player_id(uint32_t value) {
  
  _impl_.player_id_ = value;
}
inline void MoveBroadcast::set_player_id(uint32_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:MoveBroadcast.player_id)
}

// float position_x = 2;
inline void MoveBroadcast::clear_position_x() {
  _impl_.position_x_ = 0;
}
inline float MoveBroadcast::_internal_position_x() const {
  return _impl_.position_x_;
}
inline float MoveBroadcast::position_x() const {
  // @@protoc_insertion_point(field_get:MoveBroadcast.position_x)
  return _internal_position_x();
}
inline void MoveBroadcast::_internal_set_position_x(float value) {
  
  _impl_.position_x_ = value;
}
inline void MoveBroadcast::set_position_x(float value) {
  _internal_set_position_x(value);
  // @@protoc_insertion_point(field_set:MoveBroadcast.position_x)
}

// float position_y = 3;
inline void MoveBroadcast::clear_position_y() {
  _impl_.position_y_ = 0;
}
inline float MoveBroadcast::_internal_position_y() const {
  return _impl_.position_y_;
}
inline float MoveBroadcast::position_y() const {
  // @@protoc_insertion_point(field_get:MoveBroadcast.position_y)
  return _internal_position_y();
}
inline void MoveBroadcast::_internal_set_position_y(float value) {
  
  _impl_.position_y_ = value;
}
inline void MoveBroadcast::set_position_y(float value) {
  _internal_set_position_y(value);
  // @@protoc_insertion_point(field_set:MoveBroadcast.position_y)
}

// float position_z = 4;
inline void MoveBroadcast::clear_position_z() {
  _impl_.position_z_ = 0;
}
inline float MoveBroadcast::_internal_position_z() const {
  return _impl_.position_z_;
}
inline float MoveBroadcast::position_z() const {
  // @@protoc_insertion_point(field_get:MoveBroadcast.position_z)
  return _internal_position_z();
}
inline void MoveBroadcast::_internal_set_position_z(float value) {
  
  _impl_.position_z_ = value;
}
inline void MoveBroadcast::set_position_z(float value) {
  _internal_set_position_z(value);
  // @@protoc_insertion_point(field_set:MoveBroadcast.position_z)
}

// float rotation_y = 5;
inline void MoveBroadcast::clear_rotation_y() {
  _impl_.rotation_y_ = 0;
}
inline float MoveBroadcast::_internal_rotation_y() const {
  return _impl_.rotation_y_;
}
inline float MoveBroadcast::rotation_y() const {
  // @@protoc_insertion_point(field_get:MoveBroadcast.rotation_y)
  return _internal_rotation_y();
}
inline void MoveBroadcast::_internal_set_rotation_y(float value) {
  
  _impl_.rotation_y_ = value;
}
inline void MoveBroadcast::set_rotation_y(float value) {
  _internal_set_rotation_y(value);
  // @@protoc_insertion_point(field_set:MoveBroadcast.rotation_y)
}

// uint64 server_time = 6;
inline void MoveBroadcast::clear_server_time() {
  _impl_.server_time_ = uint64_t{0u};
}
inline uint64_t MoveBroadcast::_internal_server_time() const {
  return _impl_.server_time_;
}
inline uint64_t MoveBroadcast::server_time() const {
  // @@protoc_insertion_point(field_get:MoveBroadcast.server_time)
  return _internal_server_time();
}
inline void MoveBroadcast::_internal_set_server_time(uint64_t value) {
  
  _impl_.server_time_ = value;
}
inline void MoveBroadcast::set_server_time(uint64_t value) {
  _internal_set_server_time(value);
  // @@protoc_insertion_point(field_set:MoveBroadcast.server_time)
}

// uint32 state = 7;
inline void MoveBroadcast::clear_state() {
  _impl_.state_ = 0u;
}
inline uint32_t MoveBroadcast::_internal_state() const {
  return _impl_.state_;
}
inline uint32_t MoveBroadcast::state() const {
  // @@protoc_insertion_point(field_get:MoveBroadcast.state)
  return _internal_state();
}
inline void MoveBroadcast::_internal_set_state(uint32_t value) {
  
  _impl_.state_ = value;
}
inline void MoveBroadcast::set_state(uint32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:MoveBroadcast.state)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mmo_2eproto
